import os
import sys
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'DeliveryGo.settings')
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
django.setup()

from restaurant.models import Category, MenuItem

MenuItem.objects.all().delete()
Category.objects.all().delete()

categories_data = [
    {'name': 'Пиццы', 'icon': '🍕', 'order': 1, 'slug': 'pizza'},
    {'name': 'Паста', 'icon': '🍝', 'order': 2, 'slug': 'pasta'},
    {'name': 'Бургеры', 'icon': '🍔', 'order': 3, 'slug': 'burgers'},
    {'name': 'Салаты', 'icon': '🥗', 'order': 4, 'slug': 'salads'},
    {'name': 'Десерты', 'icon': '🍰', 'order': 5, 'slug': 'desserts'},
    {'name': 'Напитки', 'icon': '🥤', 'order': 6, 'slug': 'drinks'},
    {'name': 'Закуски', 'icon': '🧀', 'order': 7, 'slug': 'appetizers'},
    {'name': 'Соусы', 'icon': '🥫', 'order': 8, 'slug': 'sauces'},
]

categories = {}
for cat_data in categories_data:
    category = Category.objects.create(**cat_data)
    categories[cat_data['name']] = category

menu_items = [
    {
        'category': categories['Пиццы'],
        'name': 'Маргарита',
        'description': 'Классическая с томатами и моцареллой',
        'price': 650,
        'weight': '30 см',
        'calories': 850,
        'is_vegetarian': True,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Пепперони',
        'description': 'С острой колбаской и двойным сыром',
        'price': 750,
        'weight': '30 см',
        'calories': 920,
        'is_spicy': True,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Четыре сыра',
        'description': 'Моцарелла, горгонзола, пармезан, эмменталь',
        'price': 800,
        'weight': '30 см',
        'calories': 890,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Гавайская',
        'description': 'С курицей и ананасами',
        'price': 720,
        'weight': '30 см',
        'calories': 870,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Вегетарианская',
        'description': 'С овощами и грибами',
        'price': 680,
        'weight': '30 см',
        'calories': 760,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Мясная',
        'description': 'С беконом, ветчиной и говядиной',
        'price': 850,
        'weight': '30 см',
        'calories': 980,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Карбонара',
        'description': 'С беконом и сливками',
        'price': 780,
        'weight': '30 см',
        'calories': 910,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Диабло',
        'description': 'Очень острая с халапеньо',
        'price': 770,
        'weight': '30 см',
        'calories': 840,
        'is_spicy': True,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'С морепродуктами',
        'description': 'С креветками и кальмарами',
        'price': 950,
        'weight': '30 см',
        'calories': 820,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Детская',
        'description': 'С курицей и кукурузой',
        'price': 600,
        'weight': '25 см',
        'calories': 720,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Фирменная',
        'description': 'С копченой курицей и ананасами',
        'price': 880,
        'weight': '35 см',
        'calories': 950,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Маргарита с помидорами черри',
        'description': 'Классика со сладкими томатами',
        'price': 690,
        'weight': '30 см',
        'calories': 830,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Триколор',
        'description': 'Три вида сыра',
        'price': 820,
        'weight': '30 см',
        'calories': 880,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Капричоза',
        'description': 'С артишоками и грибами',
        'price': 780,
        'weight': '30 см',
        'calories': 810,
        'is_available': True,
    },
    {
        'category': categories['Пиццы'],
        'name': 'Римская',
        'description': 'Тонкое тесто с анчоусами',
        'price': 730,
        'weight': '30 см',
        'calories': 790,
        'is_available': True,
    },

    # ========== ПАСТА (10 блюд) ==========
    {
        'category': categories['Паста'],
        'name': 'Карбонара',
        'description': 'Спагетти с беконом и яйцами',
        'price': 550,
        'weight': '350 г',
        'calories': 650,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Паста'],
        'name': 'Болоньезе',
        'description': 'С мясным соусом и томатами',
        'price': 580,
        'weight': '350 г',
        'calories': 680,
        'is_available': True,
    },
    {
        'category': categories['Паста'],
        'name': 'Альфредо',
        'description': 'Феттучини с курицей в сливках',
        'price': 620,
        'weight': '350 г',
        'calories': 720,
        'is_available': True,
    },
    {
        'category': categories['Паста'],
        'name': 'Песто',
        'description': 'С соусом из базилика',
        'price': 530,
        'weight': '350 г',
        'calories': 610,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Паста'],
        'name': 'Арабьята',
        'description': 'Острая с чесноком и чили',
        'price': 520,
        'weight': '350 г',
        'calories': 590,
        'is_spicy': True,
        'is_available': True,
    },
    {
        'category': categories['Паста'],
        'name': 'Лазанья Болоньезе',
        'description': 'Классическая лазанья',
        'price': 680,
        'weight': '400 г',
        'calories': 780,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Паста'],
        'name': 'Равиоли с рикоттой',
        'description': 'С сыром рикотта и шпинатом',
        'price': 590,
        'weight': '300 г',
        'calories': 650,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Паста'],
        'name': 'Паста с морепродуктами',
        'description': 'С креветками и мидиями',
        'price': 750,
        'weight': '350 г',
        'calories': 710,
        'is_available': True,
    },
    {
        'category': categories['Паста'],
        'name': 'Паста с грибами',
        'description': 'Феттучини с шампиньонами',
        'price': 560,
        'weight': '350 г',
        'calories': 620,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Паста'],
        'name': 'Тортеллини со сливками',
        'description': 'С курицей в сливочном соусе',
        'price': 610,
        'weight': '300 г',
        'calories': 670,
        'is_available': True,
    },
    {
        'category': categories['Бургеры'],
        'name': 'Чизбургер',
        'description': 'С говяжьей котлетой и сыром',
        'price': 450,
        'weight': '300 г',
        'calories': 550,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Бургеры'],
        'name': 'Чикенбургер',
        'description': 'С куриной котлетой',
        'price': 420,
        'weight': '280 г',
        'calories': 480,
        'is_available': True,
    },
    {
        'category': categories['Бургеры'],
        'name': 'Вегетарианский',
        'description': 'С овощной котлетой',
        'price': 400,
        'weight': '270 г',
        'calories': 420,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Бургеры'],
        'name': 'Двойной чизбургер',
        'description': 'С двумя котлетами',
        'price': 580,
        'weight': '400 г',
        'calories': 720,
        'is_available': True,
    },
    {
        'category': categories['Бургеры'],
        'name': 'Бургер с беконом',
        'description': 'С беконом и острым соусом',
        'price': 490,
        'weight': '320 г',
        'calories': 590,
        'is_spicy': True,
        'is_available': True,
    },
    {
        'category': categories['Бургеры'],
        'name': 'Мини-бургеры',
        'description': '3 маленьких бургера',
        'price': 520,
        'weight': '350 г',
        'calories': 480,
        'is_available': True,
    },
    {
        'category': categories['Бургеры'],
        'name': 'Рыбный бургер',
        'description': 'С рыбной котлетой',
        'price': 460,
        'weight': '290 г',
        'calories': 440,
        'is_available': True,
    },
    {
        'category': categories['Бургеры'],
        'name': 'Люкс бургер',
        'description': 'С говядиной и трюфельным соусом',
        'price': 650,
        'weight': '350 г',
        'calories': 680,
        'is_available': True,
    },
    {
        'category': categories['Салаты'],
        'name': 'Греческий',
        'description': 'С фетой и оливками',
        'price': 420,
        'weight': '300 г',
        'calories': 350,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Салаты'],
        'name': 'Цезарь',
        'description': 'С курицей и пармезаном',
        'price': 450,
        'weight': '300 г',
        'calories': 480,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Салаты'],
        'name': 'Оливье',
        'description': 'Классический салат',
        'price': 380,
        'weight': '300 г',
        'calories': 420,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Салаты'],
        'name': 'С крабовыми палочками',
        'description': 'С кукурузой и яйцом',
        'price': 400,
        'weight': '300 г',
        'calories': 380,
        'is_available': True,
    },
    {
        'category': categories['Салаты'],
        'name': 'Витаминный',
        'description': 'С капустой и морковью',
        'price': 320,
        'weight': '300 г',
        'calories': 150,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Салаты'],
        'name': 'С тунцом',
        'description': 'С консервированным тунцом',
        'price': 460,
        'weight': '300 г',
        'calories': 320,
        'is_available': True,
    },
    {
        'category': categories['Салаты'],
        'name': 'С овощами гриль',
        'description': 'С баклажанами и перцем',
        'price': 390,
        'weight': '300 г',
        'calories': 280,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Салаты'],
        'name': 'С креветками',
        'description': 'С тигровыми креветками',
        'price': 520,
        'weight': '300 г',
        'calories': 310,
        'is_available': True,
    },
    {
        'category': categories['Десерты'],
        'name': 'Тирамису',
        'description': 'Итальянский десерт с маскарпоне',
        'price': 350,
        'weight': '1 порция',
        'calories': 420,
        'is_vegetarian': True,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Десерты'],
        'name': 'Панна котта',
        'description': 'Сливочный десерт с ягодами',
        'price': 320,
        'weight': '1 порция',
        'calories': 380,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Десерты'],
        'name': 'Чизкейк',
        'description': 'Сливочный чизкейк',
        'price': 380,
        'weight': '1 порция',
        'calories': 450,
        'is_vegetarian': True,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Десерты'],
        'name': 'Шоколадный фондан',
        'description': 'Тёплый шоколадный кекс',
        'price': 340,
        'weight': '1 шт',
        'calories': 410,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Десерты'],
        'name': 'Мороженое',
        'description': '3 шарика на выбор',
        'price': 250,
        'weight': '3 шарика',
        'calories': 280,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Десерты'],
        'name': 'Крем-брюле',
        'description': 'Заварной крем с карамелью',
        'price': 330,
        'weight': '1 порция',
        'calories': 390,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Десерты'],
        'name': 'Яблочный штрудель',
        'description': 'Тёплый штрудель с яблоками',
        'price': 310,
        'weight': '1 порция',
        'calories': 360,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Десерты'],
        'name': 'Профитроли',
        'description': 'Заварные пирожные с кремом',
        'price': 270,
        'weight': '5 шт',
        'calories': 340,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Напитки'],
        'name': 'Кола',
        'description': 'Газированный напиток',
        'price': 150,
        'weight': '0.5 л',
        'calories': 210,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Напитки'],
        'name': 'Лимонад',
        'description': 'Домашний с мятой',
        'price': 180,
        'weight': '0.5 л',
        'calories': 120,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Напитки'],
        'name': 'Сок апельсиновый',
        'description': 'Свежевыжатый',
        'price': 200,
        'weight': '0.3 л',
        'calories': 140,
        'is_vegetarian': True,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Напитки'],
        'name': 'Капучино',
        'description': 'Кофе с молочной пенкой',
        'price': 220,
        'weight': '0.3 л',
        'calories': 150,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Напитки'],
        'name': 'Чай черный',
        'description': 'Ароматный черный чай',
        'price': 120,
        'weight': '0.3 л',
        'calories': 5,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Напитки'],
        'name': 'Молочный коктейль',
        'description': 'Ванильный молочный коктейль',
        'price': 260,
        'weight': '0.4 л',
        'calories': 320,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Закуски'],
        'name': 'Брускетта',
        'description': 'Тосты с томатами и чесноком',
        'price': 280,
        'weight': '4 шт',
        'calories': 320,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Закуски'],
        'name': 'Сырные палочки',
        'description': 'Хрустящие с моцареллой',
        'price': 320,
        'weight': '8 шт',
        'calories': 380,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Закуски'],
        'name': 'Картофель фри',
        'description': 'Хрустящий картофель',
        'price': 220,
        'weight': '200 г',
        'calories': 320,
        'is_vegetarian': True,
        'is_bestseller': True,
        'is_available': True,
    },
    {
        'category': categories['Соусы'],
        'name': 'Чесночный',
        'description': 'Сливочный с чесноком',
        'price': 90,
        'weight': '50 мл',
        'calories': 120,
        'is_vegetarian': True,
        'is_available': True,
    },
    {
        'category': categories['Соусы'],
        'name': 'Барбекю',
        'description': 'Пикантный соус',
        'price': 85,
        'weight': '50 мл',
        'calories': 90,
        'is_spicy': True,
        'is_available': True,
    },
]

for i, item_data in enumerate(menu_items, 1):
    MenuItem.objects.create(**item_data)
    print(f"Добавлено блюдо {i}/60: {item_data['name']}")
